on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  pull_request:
      branches:
          - main

permissions:
  checks: write
  pull-requests: write

jobs:
  verify:
    runs-on: ubuntu-latest
    env:
      SHELLSPEC_VERSION: 0.28.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: install ShellSpec
        run: |
          mkdir shellspec-temp
          cd shellspec-temp
          wget https://github.com/shellspec/shellspec/archive/${{ env.SHELLSPEC_VERSION }}.tar.gz
          tar xzvf ${{ env.SHELLSPEC_VERSION }}.tar.gz
          ln -s $(realpath shellspec-${{ env.SHELLSPEC_VERSION }}/shellspec) ../shellspec
          chmod u+x ../shellspec

      - name: Run ShellSpec
        shell: sh
        run: |
          ./shellspec --output j # run tests and output in JUnit format

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: (!cancelled())
        with:
          files: |
            report/*.xml
